2025-02-19 01:05:48 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/get_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FB8888A6F0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-19 01:05:50 - Не удалось получить ответ от сервера.
2025-02-19 01:05:54 - Не удалось получить ответ от сервера.
2025-02-19 06:49:21 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/get_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A75EA5B680>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-19 06:49:23 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/sync_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A75F587DD0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-19 06:50:12 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/get_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012F398C2B70>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-19 06:50:14 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/sync_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012F39997C50>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-19 06:51:34 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/get_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012469BC2AE0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-19 06:51:36 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/sync_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012469CB7C80>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:22:57 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/get_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002639722CFE0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:22:59 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/sync_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026397243B30>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:23:31 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/get_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F3CADA2AE0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:23:33 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/sync_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F3CAEB7C80>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:24:13 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/get_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B5302F2AE0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:24:15 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/sync_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B530407C80>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:27:04 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/get_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000258C17DD8B0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:27:07 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/sync_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000258C1813E60>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:32:46 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/get_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000153B0AED820>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:32:48 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/sync_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000153B0B6C0B0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:34:13 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/get_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002310253D940>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:34:15 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/sync_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000231025744A0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:35:43 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/get_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002C15798DA60>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:35:45 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/sync_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002C1579C3F20>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:36:14 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/get_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002139837DA30>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:36:16 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/sync_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000213983B3EC0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:38:38 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/get_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E40CAC64E0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:38:40 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/sync_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E40D667C80>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:42:38 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/get_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024DA93BD3A0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:42:40 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/sync_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024DA93F6150>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 10:42:58 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/sync_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024DA94883E0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 11:16:15 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BFF735C530>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 11:16:17 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/get_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BFFA151EE0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 11:16:19 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/sync_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BFFA187E30>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 11:16:24 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/sync_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BFFA206DB0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 11:18:39 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024BBC9FC530>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 11:18:41 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/get_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024BBF881EE0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-02-20 11:18:43 - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/sync_all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024BBF8B7D70>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
